### ISSUE TITLE
When searching on DOI, the doc_id is not populated

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#69] opened 2014-11-21 16:13 UTC
I searched on using a doi of 10.1016/j.bmcl.2004.05.078 which I know is in ChEMBL

In both Chrome and FF, the Doc ID was not populated and nor was the 'Choose A Document' window - unlike when you look up PubMed ID. Even though it was found in the database

**Comment by mnowotka** [comment] 2014-11-24 16:56
If the document is found in ChEMBL `Choose A Document` windows is closed immediately. You can see that correct doc_id was found by looking at the status bar on the bottom of the curation interface. So this is not a bug but rather our different view on how `Choose a Document` window should look like and behave. So I'm closing this issue as this is directly related to https://github.com/chembl/curation-interface/issues/64

**Comment by ljbellis** [comment] 2014-11-25 17:25
You should definitely show the Doc_id in the window. 

You can't leave it blank. 

It's not directly related to #64 as that is a separate issue. That is more for aesthetics and ease of use. 

If someone does a lookup, one would expect fields to be filled. Just because there is a temporary message floating on one side doesn't mean that's acceptable. I think you will find no (or very few) examples where a look up finds a matching 'something' and fails to fill in the fields. 

Especially when it works for PubMed look up..... seems strange to have it for one and not the other.

**Comment by mnowotka** [comment] 2014-11-25 19:15
> You can't leave it blank. 

I'm not leaving it blank. I'm closing this window when it fulfilled its purpose.

> Especially when it works for PubMed look up..... seems strange to have it for one and not the other.

This is not true. It doesn't matter if you do PubMed look up or any other sort of look up. If the document is found in ChEMBL the window is closed because it's not useful anymore.

This all can be reduced to one issue - how do we think this window should behave and look like. And this is a reason why I'm:
- closing this once again as this is directly related to #64
- adding Mark in case we still don't agree 
- tagging it as `lets talk` as behavior of 'Choose a document' window should be discussed.

**Closed as completed by mnowotka** 2014-11-25 19:15 UTC
Labels: bug, lets talk :)

**Comment by ljbellis** [comment] 2014-11-28 13:55
Yes, I have seen this now works.
