### ISSUE TITLE
Why would you need a Reset Button at this stage and then to add a new document?

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#77] opened 2014-11-24 11:36 UTC
I added a new compound, chose to Insert New Compound, was asked to Choose Source, and then I saw a Reset Button, clicked it and got this Choose a Document pop up window.

What is the use of a Reset Button at this stage and why would you add a new document?

![screenshot_20](https://cloud.githubusercontent.com/assets/9843928/5164304/18daf4b8-73ce-11e4-940c-1986a2e58952.jpg)

**Comment by mnowotka** [comment] 2014-11-24 11:42
Duplicate of https://github.com/chembl/curation-interface/issues/70

**Closed as completed by mnowotka** 2014-11-24 11:42 UTC
Labels: duplicate, question
