### ISSUE TITLE
Error importing PDF

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#59] opened 2014-11-21 15:25 UTC
When trying to import a PDF into the 'Choose a document' window, it gives me the following error

![screenshot_14](https://cloud.githubusercontent.com/assets/9843928/5144477/9c2c67fe-7192-11e4-940a-e3521aa6338c.jpg)

**Comment by mnowotka** [comment] 2014-11-24 13:31
I can't reproduce this one, can you send me a pdf?

**Comment by ljbellis** [comment] 2014-11-24 14:55
I can't either. I suggest this is closed unless it's seen again?

**Comment by mnowotka** [comment] 2014-11-24 16:03
No. The pdf you provided indeed causes server error ad this issue has to be fixed.

**Comment by mnowotka** [comment] 2014-11-25 12:54
It's fixed now.

**Closed as completed by mnowotka** 2014-11-25 12:54 UTC
Labels: bug
