### ISSUE TITLE
Drug icons not updating

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#88] opened 2014-11-28 15:06 UTC
When curating this compound

http://sark.ebi.ac.uk:3021/curation/curate#1763554

when I click on Drug Icon Properties, there are two icons that are populated but not shown on the main page. 

When I change them, they still don't show on the page.

**Comment by mnowotka** [comment] 2014-11-28 16:30
Duplicate of https://github.com/chembl/curation-interface/issues/13.

**Closed as completed by mnowotka** 2014-11-28 16:30 UTC
Labels: bug, duplicate
