### ISSUE TITLE
Redraw Compound.... Make buttons available

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#45] opened 2014-11-21 10:53 UTC
When using the Redraw option, in the 'redraw compound....' pop up, I put in my old molregno and the Check and Diff buttons stay greyed out.

I would ask that as soon as you start to type in the box, these buttons become available

**Comment by mnowotka** [comment] 2014-11-21 23:03
a duplicate of #39.

**Closed as completed by mnowotka** 2014-11-21 23:03 UTC
Labels: duplicate, enhancement
